import time

from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://automationplayground.com/crm/login.html")
driver.maximize_window()
time.sleep(5)
driver.find_element(By.NAME, "email-name").send_keys("automation@gmail.com")
time.sleep(2)
driver.find_element(By.NAME, "password-name").send_keys("Password2@")
time.sleep(2)
driver.find_element(By.NAME,"submit-name").click()
time.sleep(5)
driver.find_element(By.ID,"new-customer").click()
time.sleep(5)
driver.find_element(By.ID,"EmailAddress").send_keys("email@gmail.com")
time.sleep(5)
driver.find_element(By.ID, "FirstName").send_keys("Jacob")
time.sleep(5)
driver.find_element(By.ID, "LastName").send_keys("Othniel")
time.sleep(5)
driver.find_element(By.ID, "City").send_keys("Lagos")
time.sleep(5)
driver.find_element(By.XPATH,'//*[@id="StateOrRegion"]').click()
time.sleep(5)
driver.find_element(By.XPATH, '//*[@id="StateOrRegion"]/option[5]').click()
time.sleep(5)
driver.find_element(By.NAME, "gender").click()
time.sleep(5)
driver.find_element(By.XPATH,'//*[@id="loginform"]/div/div/div/div/form/button').click()
time.sleep(5)
driver.find_element(By.XPATH,'/html/body/nav/ul/li/a').click()
time.sleep(2)
